spring.application.name=lab2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# server.port=4725

logging.level.org.springframework.security=TRACE
logging.level.org.springframework=DEBUG

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=INFO
logging.level.com.andrew=DEBUG

notification.rabbitmq.host=host.docker.internal
notification.rabbitmq.port=5672
notification.rabbitmq.username=notification
notification.rabbitmq.password=notification


spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.scheduler.instanceName=VideoComplaintScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.threadPool.threadCount=5
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=false