services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: notification-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: notification
      RABBITMQ_DEFAULT_PASS: notification
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit-data:/data

volumes:
  rabbitmq_data:
  mailpit-data:
