DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP SEQUENCE IF EXISTS tickets_seq;
DROP SEQUENCE IF EXISTS events_seq;
DROP SEQUENCE IF EXISTS users_seq;
DROP TYPE IF EXISTS ticket_type;