spring.application.name=lab1

spring.datasource.url=jdbc:postgresql://localhost:5432/studs

# spring.datasource.jndi-name=java:jboss/datasources/MyPostgresDS
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# server.port=4725

# logging.level.org.springframework.security=TRACE

# logging.level.org.springframework=DEBUG
# debug=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
spring.jpa.properties.hibernate.transaction.coordinator_class=jta
spring.jpa.properties.hibernate.current_session_context_class=jta

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossStandAloneJtaPlatform
# spring.jpa.properties.hibernate.transaction.coordinator_class=jta

logging.level.root=INFO
logging.level.com.andrew=DEBUG

# spring.datasource.username=s408498
# spring.datasource.password=Cm9TbTotPIve1n4s