spring.application.name=lab2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# server.port=4725

logging.level.org.springframework.security=TRACE
logging.level.org.springframework=DEBUG

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=INFO
logging.level.com.andrew=DEBUG